### ISSUE TITLE
Warps.yml Deletes or Deletes Data on Server Restart

### ISSUE THREAD

**Issue by cleverwind** [NerdsWBNerds/EasyWarp#10]
Spigot 1.8
GriefPrevention
WorldLoad
bPermissions
CoreProtect
EasyWarp 3.3

Every time I reboot the server, or even stop/start, if the warps.yml doesn't delete itself, it deletes all contents within the file. 

All warps were initially created in game and functional, including in/out of additional maps beyond the main world. If I have to stop the server, I have to drop in a locally saved warps.yml (or data.yml depending on whether I'm using the plugin from EasyWarp or Easy-Warp - have tried both) before starting the server.

I have not edited the config.yml 

This issue began before installing bPermissions.

**Comment by NerdsWBNerds** [comment]
Deleting warps fixed in 3.4 (hopefully)
http://dev.bukkit.org/bukkit-plugins/easy-warp/files/20-easy-warp-v3-4/
