### ISSUE TITLE
Doesn't ignore case

### ISSUE THREAD

**Issue by nicosiimon** [NerdsWBNerds/EasyWarp#12]
I really like this plugin but my only problem is that it doesn't ignore Upper/Lower case writing in warp names. If you set a warp /setwarp WaRp you have to teleport there by /warp warp and you can't use /warp WaRp. I hope you get my point.

Best regards
~Nico

**Comment by NerdsWBNerds** [comment]
Fixed in 3.4
http://dev.bukkit.org/bukkit-plugins/easy-warp/files/20-easy-warp-v3-4/
