### ISSUE TITLE
warp signs

### ISSUE THREAD

**Issue by jklll1810** [NerdsWBNerds/EasyWarp#8]
non ops cant use warp signs

**Comment by jjthomas3** [comment]
Every time I restart the server it wipes out all the warps and writes out the default config. 
I am running Spigot 1.8.7, some times it also will suddenly decide to dislike a saved warp and will throw an exception when users attempt top use the warp

**Comment by cleverwind** [comment]
I am using Spigot 1.8.8 and have the exact same issue, but for me it wipes the warps.yml (perhaps my version uses warps.yml where yours uses config.yml).  My config.yml file mostly contains in-game response messages to commands executed. 

I didn't notice this issue upon immediate install, but after a reboot or two it became apparent. I now have a locally saved file warps.yml that I have to remember to drop in after every stop or reboot, or none of the warps will work. 

I've initiated a ticket concerning this issue as well.

Additionally, sometimes the warps will work between worlds and sometimes they won't - I can't track what the variables might be, and I'm seeing no output errors.

**Comment by cleverwind** [comment]
Non-ops can use the signs, usually.... jklll1810, perhaps you have some other permissions setting conflicting?

**Comment by NerdsWBNerds** [comment]
Deleting warps fixed in 3.4 (hopefully)
http://dev.bukkit.org/bukkit-plugins/easy-warp/files/20-easy-warp-v3-4/

Non-OP seems to be more of an issue with incorrect config/player permissions.  Try taking a look at your config
